2021-04-25 16:41:17,001 INFO    MainThread:45359 [wandb_setup.py:_flush():69] setting env: {}
2021-04-25 16:41:17,002 INFO    MainThread:45359 [wandb_setup.py:_flush():69] setting login settings: {}
2021-04-25 16:41:17,002 INFO    MainThread:45359 [wandb_init.py:_log_setup():336] Logging user logs to /md0/home/btilmon/projects/learncfa_pytorch/wandb/run-20210425_164116-3ordyx98/logs/debug.log
2021-04-25 16:41:17,002 INFO    MainThread:45359 [wandb_init.py:_log_setup():337] Logging internal logs to /md0/home/btilmon/projects/learncfa_pytorch/wandb/run-20210425_164116-3ordyx98/logs/debug-internal.log
2021-04-25 16:41:17,003 INFO    MainThread:45359 [wandb_init.py:init():369] calling init triggers
2021-04-25 16:41:17,003 INFO    MainThread:45359 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {}
2021-04-25 16:41:17,003 INFO    MainThread:45359 [wandb_init.py:init():418] starting backend
2021-04-25 16:41:17,003 INFO    MainThread:45359 [backend.py:_multiprocessing_setup():71] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-04-25 16:41:17,020 INFO    MainThread:45359 [backend.py:ensure_launched():123] starting backend process...
2021-04-25 16:41:17,027 INFO    MainThread:45359 [backend.py:ensure_launched():128] started backend process with pid: 45375
2021-04-25 16:41:17,028 INFO    MainThread:45359 [wandb_init.py:init():423] backend started and connected
2021-04-25 16:41:17,030 INFO    MainThread:45359 [wandb_init.py:init():463] updated telemetry
2021-04-25 16:41:17,031 INFO    MainThread:45359 [wandb_init.py:init():482] communicating current version
2021-04-25 16:41:17,715 INFO    MainThread:45359 [wandb_init.py:init():487] got version response upgrade_message: "wandb version 0.10.27 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-04-25 16:41:17,716 INFO    MainThread:45359 [wandb_init.py:init():495] communicating run to backend with 30 second timeout
2021-04-25 16:41:17,945 INFO    MainThread:45359 [wandb_init.py:init():520] starting run threads in backend
2021-04-25 16:41:18,010 INFO    MainThread:45359 [wandb_run.py:_console_start():1524] atexit reg
2021-04-25 16:41:18,011 INFO    MainThread:45359 [wandb_run.py:_redirect():1371] redirect: SettingsConsole.REDIRECT
2021-04-25 16:41:18,012 INFO    MainThread:45359 [wandb_run.py:_redirect():1376] Redirecting console.
2021-04-25 16:41:18,015 INFO    MainThread:45359 [wandb_run.py:_redirect():1438] Redirects installed.
2021-04-25 16:41:18,016 INFO    MainThread:45359 [wandb_init.py:init():544] run started, returning control to user process
2021-04-25 16:41:30,887 INFO    MainThread:45359 [wandb_run.py:_atexit_cleanup():1494] got exitcode: 255
2021-04-25 16:41:30,887 INFO    MainThread:45359 [wandb_run.py:_restore():1466] restore
2021-04-25 16:41:33,083 INFO    MainThread:45359 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 758
  total_bytes: 758
}

2021-04-25 16:41:33,472 INFO    MainThread:45359 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 758
  total_bytes: 758
}

2021-04-25 16:41:33,977 INFO    MainThread:45359 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 758
  total_bytes: 1966
}

2021-04-25 16:41:34,145 INFO    MainThread:45359 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 758
  total_bytes: 1966
}

2021-04-25 16:41:34,248 INFO    MainThread:45359 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1966
  total_bytes: 1966
}

2021-04-25 16:41:34,351 INFO    MainThread:45359 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1966
  total_bytes: 1966
}

2021-04-25 16:41:34,453 INFO    MainThread:45359 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1966
  total_bytes: 1966
}

2021-04-25 16:41:34,556 INFO    MainThread:45359 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1966
  total_bytes: 1966
}

2021-04-25 16:41:34,659 INFO    MainThread:45359 [wandb_run.py:_wait_for_finish():1616] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1966
  total_bytes: 1966
}

2021-04-25 16:41:35,819 INFO    MainThread:45359 [wandb_run.py:_show_files():1838] logging synced files
