2021-04-26 09:13:29,272 INFO    MainThread:31931 [wandb_setup.py:_flush():69] setting env: {}
2021-04-26 09:13:29,273 INFO    MainThread:31931 [wandb_setup.py:_flush():69] setting login settings: {}
2021-04-26 09:13:29,273 INFO    MainThread:31931 [wandb_init.py:_log_setup():336] Logging user logs to /md0/home/btilmon/projects/learncfa_pytorch/wandb/run-20210426_091329-s3v4uivp/logs/debug.log
2021-04-26 09:13:29,273 INFO    MainThread:31931 [wandb_init.py:_log_setup():337] Logging internal logs to /md0/home/btilmon/projects/learncfa_pytorch/wandb/run-20210426_091329-s3v4uivp/logs/debug-internal.log
2021-04-26 09:13:29,273 INFO    MainThread:31931 [wandb_init.py:init():369] calling init triggers
2021-04-26 09:13:29,273 INFO    MainThread:31931 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {}
2021-04-26 09:13:29,273 INFO    MainThread:31931 [wandb_init.py:init():418] starting backend
2021-04-26 09:13:29,273 INFO    MainThread:31931 [backend.py:_multiprocessing_setup():71] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-04-26 09:13:29,287 INFO    MainThread:31931 [backend.py:ensure_launched():123] starting backend process...
2021-04-26 09:13:29,292 INFO    MainThread:31931 [backend.py:ensure_launched():128] started backend process with pid: 31947
2021-04-26 09:13:29,293 INFO    MainThread:31931 [wandb_init.py:init():423] backend started and connected
2021-04-26 09:13:29,295 INFO    MainThread:31931 [wandb_init.py:init():463] updated telemetry
2021-04-26 09:13:29,296 INFO    MainThread:31931 [wandb_init.py:init():482] communicating current version
2021-04-26 09:13:30,031 INFO    MainThread:31931 [wandb_init.py:init():487] got version response upgrade_message: "wandb version 0.10.27 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-04-26 09:13:30,031 INFO    MainThread:31931 [wandb_init.py:init():495] communicating run to backend with 30 second timeout
2021-04-26 09:13:30,217 INFO    MainThread:31931 [wandb_init.py:init():520] starting run threads in backend
2021-04-26 09:13:30,287 INFO    MainThread:31931 [wandb_run.py:_console_start():1524] atexit reg
2021-04-26 09:13:30,288 INFO    MainThread:31931 [wandb_run.py:_redirect():1371] redirect: SettingsConsole.REDIRECT
2021-04-26 09:13:30,288 INFO    MainThread:31931 [wandb_run.py:_redirect():1376] Redirecting console.
2021-04-26 09:13:30,292 INFO    MainThread:31931 [wandb_run.py:_redirect():1438] Redirects installed.
2021-04-26 09:13:30,292 INFO    MainThread:31931 [wandb_init.py:init():544] run started, returning control to user process
2021-04-26 09:13:35,680 INFO    MainThread:31931 [wandb_run.py:_atexit_cleanup():1494] got exitcode: 0
2021-04-26 09:13:35,683 INFO    MainThread:31931 [wandb_run.py:_restore():1466] restore
2021-04-26 09:13:37,861 INFO    MainThread:31931 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 758
  total_bytes: 758
}

2021-04-26 09:13:38,345 INFO    MainThread:31931 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 758
  total_bytes: 758
}

2021-04-26 09:13:39,237 INFO    MainThread:31931 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 758
  total_bytes: 1985
}

2021-04-26 09:13:39,423 INFO    MainThread:31931 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 758
  total_bytes: 1985
}

2021-04-26 09:13:39,526 INFO    MainThread:31931 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1985
  total_bytes: 1985
}

2021-04-26 09:13:39,628 INFO    MainThread:31931 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1985
  total_bytes: 1985
}

2021-04-26 09:13:39,731 INFO    MainThread:31931 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1985
  total_bytes: 1985
}

2021-04-26 09:13:39,833 INFO    MainThread:31931 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1985
  total_bytes: 1985
}

2021-04-26 09:13:39,935 INFO    MainThread:31931 [wandb_run.py:_wait_for_finish():1616] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1985
  total_bytes: 1985
}

2021-04-26 09:13:41,069 INFO    MainThread:31931 [wandb_run.py:_show_files():1838] logging synced files
